Code/MathHub/MathHub.Web/Controllers/ProblemController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MathHub.Core.Interfaces.Comments;
using MathHub.Core.Interfaces.Problems;
using MathHub.Entity.Entity;
using MathHub.Framework.Controllers;
using AutoMapper;
using MathHub.Web.Models.ProblemVM;
using MathHub.Core.Config;
using MathHub.Web.CustomAnnotation.ActionFilter;
using WebMatrix.WebData;
using MathHub.Core.Infrastructure;
using MathHub.Web.Models.CommonVM;

namespace MathHub.Web.Controllers
{
    public partial class ProblemController : BaseController
    {

        #region Constructor
        private IProblemQueryService _problemQueryService;
        private IProblemCommandService _problemCommandService;
        private ICommentCommandService _commentCommandService;
        private IAuthenticationService _authenticationService;

        public ProblemController(
            IProblemQueryService problemQueryService,
            ICommentCommandService commentCommandService,
            IProblemCommandService problemCommandService,
            IAuthenticationService authenticationService)
        {
            _problemQueryService = problemQueryService;
            _commentCommandService = commentCommandService;
            _problemCommandService = problemCommandService;
            _authenticationService = authenticationService;
        }
        #endregion

        #region GET Problem
        // GET /Problem
        public virtual ActionResult Index()
        {
            return RedirectToAction(MathHub.Core.Config.RouteDefaults.DEFAULT_PROBLEM_TAB);
        }

        // GET /Problem/Trending
        public virtual ActionResult Trending()
        {
            return View("Views/ListAllProblem");
        }

        // GET /Problem/Mytags
        public virtual ActionResult Mytags()
        {
            return View("Views/ListAllProblem");
        }

        // GET /Problem/Unanswered
        public virtual ActionResult Unanswered()
        {
            return View("Views/ListAllProblem");
        }

        // GET /Problem/Newest
        public virtual ActionResult Newest()
        {
            IEnumerable<Problem> problems =
                _problemQueryService.GetNewestProblems(
                Constant.DEFAULT_OFFSET, Constant.DEFAULT_PER_PAGE);

            ICollection<PreviewProblemVM> problemVms =
                problems.Select(Mapper.Map<Problem, PreviewProblemVM>).ToList();

            return View("Views/ListAllProblem", problemVms);
        }

        [Authorize]
        [HttpGet]
        // GET /Problem/Create
        public virtual ActionResult Create()
        {
            return View("Views/CreateProblem");
        }

        // GET /Problem/Detail/1
        public virtual ActionResult Detail(int id)
        {
            Problem targetProblem = _problemQueryService.GetProblemById(id);

            // Map from Model to ViewModel
            DetailProblemVM problemViewModel =
                Mapper.Map<Problem, DetailProblemVM>(targetProblem);


            problemViewModel.CommentPostVm = new CommentPostVM();
            problemViewModel.CommentPostVm.MainPostId = problemViewModel.Id;
            problemViewModel.CommentPostVm.Type = EnumCommentType.QUESTION;

            // this mapping must be have
            // if nott. strange error will appear at ViewModel in View
            problemViewModel.AnswerPostVm = new AnswerPostVM();
            problemViewModel.AnswerPostVm.MainPostId = problemViewModel.Id;

            problemViewModel.HintPostVm = new HintPostVM();
            problemViewModel.HintPostVm.MainPostId = problemViewModel.Id;

            return View("Views/DetailProblem", problemViewModel);
        }

        #endregion

        #region POST Problem
        // POST /Problem/Create
        [Authorize]
        [HttpPost, ValidateInput(false)]
        public virtual ActionResult Create(CreateProblemVM problemVM)
        {
            if (ModelState.IsValid)
            {
                // create new problem
                Problem p = new Problem();
                p.UserId = _authenticationService.GetUserId();
                p.Title = problemVM.Title;
                p.Content = problemVM.Content;
                p.DateCreated = DateTime.Now;
                p.DateModified = DateTime.Now;
                bool res = _problemCommandService.AddProblem(p);
                if (!res)
                {
                    // by some reason. cannot create problem
                    ModelState.AddModelError("create_problem_exception", "This problem cannot be created. Try again later");
                    return View("Views/CreateProblem", problemVM);
                }
                else
                {
                    return Detail(p.Id);
                }
            }
            else
            {
                // if not ModelState valid
                ModelState.AddModelError("model_state_invalid", "Current State is Invalid");
                return View("Views/CreateProblem", problemVM);
            }
        } 
        #endregion
    }
}

Code/MathHub/MathHub.Web/Views/Problem/Partials/_AnswerItem.cshtml
@model MathHub.Web.Models.ProblemVM.AnswerItemVM

<script type="text/javascript">
	$(document).ready(function () {
		// load comments of reply
		getReplyComments('reply-comments-@Model.Id', @Model.Id, 0);
	});
</script>

Answer Item @Model.Content<br/>

<h3>Comments</h3>
@* ajax insert comment here to problem-comments *@
<div id="reply-comments-@Model.Id"></div>

@*  when click "Get More Comments" will appears all comments and a post form to post comment for reply *@
@if(Model.CommentNum > 5)
{
	// hide `add comment`, load more comments and appear post form
	// function showCommentOnClick(commentListId, postId, formId, hideId)
	<button id="add-reply-comment" 
		onclick="showCommentOnClick('reply-comments-@Model.Id', @Model.Id, 'comment-post-form-@Model.Id', 'add-reply-comment')">
		Add / Show @{int num = Model.CommentNum - 5; } @num more comments
	</button>
}else
{
	// hide `add comment` button and show post form
	// function showAndHideElementsById(showId, hideId)
	<button id="add-reply-comment" 
		onclick="showAndHideElementsById('comment-post-form-@Model.Id', 'add-reply-comment')">Add comments</button>
}

@Html.Partial("Partials/_CommentReplyPostForm", @Model.CommentPostVm)
<br />

Code/MathHub/MathHub.Web/Views/Problem/Partials/_AnswerList.cshtml
@model MathHub.Web.Models.ProblemVM.AnswerListVM
@{
    foreach(MathHub.Web.Models.ProblemVM.AnswerItemVM answer in Model.AnswerItemVms)
    {
        @Html.Partial("Partials/_AnswerItem", answer);
    }

}

Code/MathHub/MathHub.Web/Views/Problem/Partials/_AnswerPostForm.cshtml
@model MathHub.Web.Models.ProblemVM.AnswerPostVM

    @using (Html.BeginForm("AddAnswer", "Problem", FormMethod.Post, 
                            new {id = "answer-post-form" }))
    {
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content)
        @Html.ValidationMessageFor(m => m.Content)

        @Html.HiddenFor(m => m.MainPostId)

        @* function postAnswer(formId, answerDivId) *@
        <input type="button" name="addAnswer" onclick="postAnswer('answer-post-form', 'problem-answers')" value="Send"/>
    }

Code/MathHub/MathHub.Web/Views/Problem/Partials/_CommentItem.cshtml
@model MathHub.Web.Models.ProblemVM.CommentItemVM

Comment Item @Model.Content - @Model.UserUsername<br/>

Code/MathHub/MathHub.Web/Views/Problem/Partials/_CommentList.cshtml
@using MathHub.Web.Models.ProblemVM
@model CommentListVM
@{
    foreach (CommentItemVM comment in Model.CommentItemVms)
    {
        @Html.Partial("Partials/_CommentItem", comment)
    }
}

Code/MathHub/MathHub.Web/Views/Problem/Partials/_CommentProblemPostForm.cshtml
@model MathHub.Web.Models.ProblemVM.CommentPostVM

    @using (Html.BeginForm("AddComment", "Problem", FormMethod.Post,  
        new {style = "display:none", id = "comment-post-form-" + @Model.MainPostId}))
    {
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content)
        @Html.ValidationMessageFor(m => m.Content)

        @Html.HiddenFor(m => m.MainPostId)
        @Html.HiddenFor(m => m.Type)

        @* function postComment(formId, commentDivId) *@
        @* post form - form to append data *@
        <input type="button" name="add-comment" 
            onclick="postComment('comment-post-form-@Model.MainPostId', 'problem-comments')" value="Send"></input>
    }

Code/MathHub/MathHub.Web/Views/Problem/Partials/_CommentReplyPostForm.cshtml
@model MathHub.Web.Models.ProblemVM.CommentPostVM

    @using (Html.BeginForm("AddComment", "Problem", FormMethod.Post,  
        new {style = "display:none", id = "comment-post-form-" + @Model.ReplyId}))
    {
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content)
        @Html.ValidationMessageFor(m => m.Content)

        @Html.HiddenFor(m => m.ReplyId)
        @Html.HiddenFor(m => m.Type)

        @* function postComment(formId, commentDivId) *@
        @* post form - form to append data *@
        <input type="button" name="add-comment" 
            onclick="postComment('comment-post-form-@Model.ReplyId', 'reply-comments-@Model.ReplyId')" value="Send"/>
    }

Code/MathHub/MathHub.Web/Views/Problem/Partials/_HintItem.cshtml
@model MathHub.Web.Models.ProblemVM.HintItemVM

<script type="text/javascript">
	$(document).ready(function () {
		// load comments of reply for hint
		getReplyComments('reply-comments-@Model.Id', @Model.Id, 0);
	});
</script>

Hint Item @Model.Content<br/>

<h3>Comments</h3>
@* ajax insert comment here to problem-comments *@
<div id="reply-comments-@Model.Id"></div>

@*  when click "Get More Comments" will appears all comments and a post form to post comment for reply *@
@if(Model.CommentNum > 5)
{
	// hide `add comment`, load more comments and appear post form
	// function showCommentOnClick(commentListId, postId, formId, hideId)
	<button id="add-reply-comment" 
		onclick="showCommentOnClick('reply-comments-@Model.Id', @Model.Id, 'comment-post-form-@Model.Id', 'add-reply-comment')">
		Add / Show @{int num = Model.CommentNum - 5; } @num more comments
	</button>
}else
{
	// hide `add comment` button and show post form
	// function showAndHideElementsById(showId, hideId)
	<button id="add-reply-comment" 
		onclick="showAndHideElementsById('comment-post-form-@Model.Id', 'add-reply-comment')">Add comments</button>
}

@Html.Partial("Partials/_CommentReplyPostForm", @Model.CommentPostVm)
<br />

Code/MathHub/MathHub.Web/Views/Problem/Partials/_HintList.cshtml
@model MathHub.Web.Models.ProblemVM.HintListVM
@{
    foreach (MathHub.Web.Models.ProblemVM.HintItemVM hintItemVm in Model.HintItemVms)
    {
        @Html.Partial("Partials/_HintItem", hintItemVm);
    }
    

}

Code/MathHub/MathHub.Web/Views/Problem/Partials/_HintPostForm.cshtml
@model MathHub.Web.Models.ProblemVM.HintPostVM

    @using (Html.BeginForm("AddHint", "Problem", FormMethod.Post, 
                            new {id = "hint-post-form" }))
    {
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content)
        @Html.ValidationMessageFor(m => m.Content)

        @Html.HiddenFor(m => m.MainPostId)

        @* function postHint(formId, hintDivId) *@
        <input type="button" name="addHint" onclick="postHint('hint-post-form', 'problem-hints')" value="Send"/>
    }

Code/MathHub/MathHub.Web/Views/Problem/Partials/_ProblemItem.cshtml
@model MathHub.Web.Models.ProblemVM.PreviewProblemVM





@Html.ActionLink("Problem item " + Model.Title,
                 "Detail", new {controller = "Problem", id = Model.Id})<br/>
<ul>

    <li>Id:@Html.Raw(@Model.Id) </li>
    <li>Content: @Html.Raw(@Model.Content) </li>
    <li>DateCreated: @Model.DateCreated </li>
    <li>DateModified: @Model.DateModified </li>
    <li>UserId: @Model.UserId </li>
    <li>Title: @Html.Raw(@Model.Title) </li>
    <li>FavoriteNum: @Model.FavoriteNum </li>
    <li>ReportNum: @Model.FavoriteNum </li>
    <li>ShareNum: @Model.ShareNum </li>
    <li>VoteUpNum: @Model.VoteUpNum</li>
    <li>VoteDownNum: @Model.VoteDownNum </li>
    <li>AnswerNum: @Model.AnswerNum </li>
    <li>HintNum: @Model.HintNum </li>
</ul>